### PR TITLE
Implement astrouxds

### PR DESCRIPTION
**Pull request by thkruz**

### CODE REVIEW

**Review by tkbdsi — APPROVED** [review]
Looks like it was just a refactor of pushing the styled-components into separate component files, which I'm good with. Also adds in the astro-web-components, which I saw in your Discussion, so +1. 

I only used styled-components in order to give some sort of shell/structure. I'm also cool with them being phased out as they are replaced with some other styling (as long as we still pass the instructor's wishes, haha).

**Comment by thkruz** [comment]
## Notes
-  Switched to getByTestId for header.test. There are some oddities about this library and I don't have time tonight to figure out the roles - but this ensured the tests remain functioning
- You have to stop babel from transforming @astrouxds/react (see package.json) or you get tons of linter and jest errors

**Comment by thkruz** [comment]
The issue was that I added the special code for getting jest to work...and then had the pipeline run a different script...

**Comment by tkbdsi** [comment]
Ah, ok, no problem. I am good with the overall changes. So merge aaawwwwayyyyyy

**Comment by thkruz** [comment]
> I only used styled-components in order to give some sort of shell/structure. I'm also cool with them being phased out as they are replaced with some other styling (as long as we still pass the instructor's wishes, haha).

I absolutely hate them because we are just adding CSS and giving it a new name - but when you use actual CSS you get syntax coloring. That said...the "customer" wants them, so I'll happily play the game.

**Pull request merged**
